services:

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: "keycloak-credit"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
    ports:
      - 8090:8080
